/**
 * OnboardingComposer — pure renderer for .bober/onboarding/ markdown artifacts.
 *
 * Key design invariants:
 * - render() is PURE. No I/O. Same inputs → same outputs.
 * - writeAll() is the ONLY method that touches disk.
 * - Marker convention guards human edits from being overwritten.
 * - All markdown output is GFM-compatible (no extensions).
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { OnboardingInputs, OnboardingArtifacts } from "./types.js";

// ── Marker ─────────────────────────────────────────────────────────

const MARKER = "<!-- generated by agent-bober — DO NOT EDIT below this line -->";

// ── Pure renderer ─────────────────────────────────────────────────

export class OnboardingComposer {
  /**
   * Pure renderer. Takes typed inputs, returns 5 markdown strings.
   * No I/O. No side effects. Deterministic.
   */
  render(inputs: OnboardingInputs): OnboardingArtifacts {
    return {
      readme: renderReadme(inputs),
      architectureOverview: renderArchitectureOverview(inputs),
      hotspots: renderHotspots(inputs),
      knowledgeGaps: renderKnowledgeGaps(inputs),
      communities: renderCommunities(inputs),
    };
  }

  /**
   * Write all 5 artifacts to `dir`, creating it if necessary.
   *
   * Marker convention:
   * - File absent → write `${MARKER}\n\n${content}`.
   * - File with marker → preserve everything above, replace below with `${MARKER}\n\n${content}`.
   * - File without marker → throw with clear error (refuse to clobber user content).
   *
   * @param artifacts Result of render()
   * @param dir       Target directory (created if missing)
   */
  async writeAll(artifacts: OnboardingArtifacts, dir: string): Promise<void> {
    if (!dir || dir.trim() === "") {
      throw new Error("writeAll: dir argument must be a non-empty path.");
    }

    await mkdir(dir, { recursive: true });

    const files: Array<[string, string]> = [
      ["README.md", artifacts.readme],
      ["architecture-overview.md", artifacts.architectureOverview],
      ["hotspots.md", artifacts.hotspots],
      ["knowledge-gaps.md", artifacts.knowledgeGaps],
      ["communities.md", artifacts.communities],
    ];

    for (const [filename, content] of files) {
      await writeWithMarker(join(dir, filename), content);
    }
  }
}

// ── File write helper ─────────────────────────────────────────────

async function writeWithMarker(filePath: string, content: string): Promise<void> {
  let existing: string | null = null;
  try {
    existing = await readFile(filePath, "utf-8");
  } catch (err) {
    // File doesn't exist — proceed with fresh write
    if ((err as { code?: string }).code !== "ENOENT") {
      throw err;
    }
  }

  if (existing === null) {
    // File doesn't exist — write with marker
    await writeFile(filePath, `${MARKER}\n\n${content}`, "utf-8");
    return;
  }

  const markerIndex = existing.indexOf(MARKER);
  if (markerIndex === -1) {
    // File exists but has no marker — refuse to overwrite
    const file = filePath.split("/").pop() ?? filePath;
    throw new Error(
      `Refusing to overwrite ${file}: missing generation marker. Add the marker manually or delete the file.`,
    );
  }

  // File has marker — preserve above, replace below
  const above = existing.slice(0, markerIndex);
  await writeFile(filePath, `${above}${MARKER}\n\n${content}`, "utf-8");
}

// ── README.md renderer ────────────────────────────────────────────

function renderReadme(inputs: OnboardingInputs): string {
  const generatedAt = new Date().toISOString();
  const { tokensaveVersion, indexedFileCount } = inputs.status;

  const lines: string[] = [];
  lines.push("# Onboarding — agent-bober graph");
  lines.push("");
  lines.push(`_Generated at: ${generatedAt}_`);
  lines.push("");
  lines.push(
    `This codebase is indexed with agent-bober graph v${tokensaveVersion}. ` +
    `The graph currently covers ${indexedFileCount} ${indexedFileCount === 1 ? "file" : "files"}. ` +
    `Use the documents below to quickly orient yourself to the architecture, locate high-complexity areas, ` +
    `identify potentially unused code, and understand how modules are grouped into communities.`,
  );
  lines.push("");
  lines.push("## Where to look");
  lines.push("");
  lines.push("- [Architecture Overview](./architecture-overview.md) — public API per module");
  lines.push("- [Hotspots](./hotspots.md) — high-complexity symbols worth reviewing");
  lines.push("- [Knowledge Gaps](./knowledge-gaps.md) — dead code and uncalled public APIs");
  lines.push("- [Communities](./communities.md) — module groupings");
  lines.push("- [README](./README.md) — this file");

  return lines.join("\n");
}

// ── architecture-overview.md renderer ────────────────────────────

function renderArchitectureOverview(inputs: OnboardingInputs): string {
  const lines: string[] = [];
  lines.push("# Architecture Overview");
  lines.push("");

  // Dedup modules: if duplicates exist, merge their symbols
  const merged = mergeModuleApis(inputs.moduleApis);
  // Sort alphabetically by module name
  const sorted = merged.slice().sort((a, b) => a.module.localeCompare(b.module));

  if (sorted.length === 0) {
    lines.push("_No modules found._");
    return lines.join("\n");
  }

  for (const mod of sorted) {
    lines.push(`## ${escapeMarkdown(mod.module)}`);
    lines.push("");
    if (mod.symbols.length === 0) {
      lines.push("_No public API symbols._");
    } else {
      for (const sym of mod.symbols) {
        lines.push(`- \`${sym.name}\` — ${sym.file}:${sym.line}`);
      }
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd();
}

// ── hotspots.md renderer ──────────────────────────────────────────

function renderHotspots(inputs: OnboardingInputs): string {
  const lines: string[] = [];
  lines.push("# Hotspots");
  lines.push("");

  if (inputs.hotspots.length === 0) {
    lines.push("No hotspots detected in this codebase.");
    return lines.join("\n");
  }

  // Separate valid scores from NaN scores; sort valid desc, NaN last
  const withScore = inputs.hotspots.filter((h) => !isNaN(h.score));
  const nanEntries = inputs.hotspots.filter((h) => isNaN(h.score));

  const sorted = [
    ...withScore.slice().sort((a, b) => b.score - a.score),
    ...nanEntries,
  ].slice(0, 20);

  lines.push("| Symbol | File:Line | Complexity Score | Why it matters |");
  lines.push("| --- | --- | --- | --- |");

  for (const h of sorted) {
    const symbol = escapePipe(h.symbol);
    const fileLine = escapePipe(`${h.file}:${h.line}`);
    const score = isNaN(h.score) ? "score unavailable" : String(h.score);
    const reason = escapePipe(h.reason ?? "");
    lines.push(`| ${symbol} | ${fileLine} | ${score} | ${reason} |`);
  }

  return lines.join("\n");
}

// ── knowledge-gaps.md renderer ────────────────────────────────────

function renderKnowledgeGaps(inputs: OnboardingInputs): string {
  const lines: string[] = [];
  lines.push("# Knowledge Gaps");
  lines.push("");

  // Dead code section
  lines.push("## Potentially unused (dead code)");
  lines.push("");
  if (inputs.deadCode.length === 0) {
    lines.push("No dead code detected.");
  } else {
    for (const dc of inputs.deadCode) {
      lines.push(`- \`${dc.symbol}\` — ${dc.file}:${dc.line}`);
    }
  }
  lines.push("");

  // Public APIs without internal callers
  const uncalledSymbols: Array<{ module: string; name: string; file: string; line: number }> = [];
  for (const mod of inputs.moduleApis) {
    for (const sym of mod.symbols) {
      if (!sym.hasInternalCallers) {
        uncalledSymbols.push({ module: mod.module, name: sym.name, file: sym.file, line: sym.line });
      }
    }
  }

  lines.push("## Public APIs without internal callers");
  lines.push("");
  if (uncalledSymbols.length === 0) {
    lines.push("All public APIs have internal callers.");
  } else {
    for (const sym of uncalledSymbols) {
      lines.push(`- \`${sym.name}\` (${sym.module}) — ${sym.file}:${sym.line}`);
    }
  }

  return lines.join("\n");
}

// ── communities.md renderer ───────────────────────────────────────

function renderCommunities(inputs: OnboardingInputs): string {
  const lines: string[] = [];
  lines.push("# Communities");
  lines.push("");

  // Group merged modules by community field
  const merged = mergeModuleApis(inputs.moduleApis);

  const communityMap = new Map<string, typeof merged>();
  for (const mod of merged) {
    const community = mod.community ?? "uncategorized";
    if (!communityMap.has(community)) {
      communityMap.set(community, []);
    }
    communityMap.get(community)!.push(mod);
  }

  if (communityMap.size === 0) {
    lines.push("_No communities found._");
    return lines.join("\n");
  }

  // Sort communities alphabetically
  const sortedCommunities = Array.from(communityMap.entries()).sort(([a], [b]) =>
    a.localeCompare(b),
  );

  for (const [community, mods] of sortedCommunities) {
    const totalSymbols = mods.reduce((sum, m) => sum + m.symbols.length, 0);
    lines.push(`## ${escapeMarkdown(community)}`);
    lines.push("");
    lines.push(
      `Module group with ${mods.length} ${mods.length === 1 ? "module" : "modules"} and ${totalSymbols} ${totalSymbols === 1 ? "symbol" : "symbols"}.`,
    );
    lines.push("");
    for (const mod of mods.slice().sort((a, b) => a.module.localeCompare(b.module))) {
      lines.push(`- ${escapeMarkdown(mod.module)}`);
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd();
}

// ── Helpers ───────────────────────────────────────────────────────

type MergedModule = {
  module: string;
  community?: string;
  symbols: Array<{ name: string; file: string; line: number; hasInternalCallers: boolean }>;
};

/**
 * Merge duplicate module names. If the same module name appears more than once,
 * merge their symbols (dedup by name+file+line). Community: use first non-undefined value.
 */
function mergeModuleApis(
  moduleApis: OnboardingInputs["moduleApis"],
): MergedModule[] {
  const seen = new Map<string, MergedModule>();

  for (const mod of moduleApis) {
    const existing = seen.get(mod.module);
    if (!existing) {
      seen.set(mod.module, {
        module: mod.module,
        community: mod.community,
        symbols: [...mod.symbols],
      });
    } else {
      // Merge symbols
      const symKeys = new Set(existing.symbols.map((s) => `${s.name}:${s.file}:${s.line}`));
      for (const sym of mod.symbols) {
        const key = `${sym.name}:${sym.file}:${sym.line}`;
        if (!symKeys.has(key)) {
          symKeys.add(key);
          existing.symbols.push(sym);
        }
      }
      // Preserve community from first entry with a defined value
      if (existing.community === undefined && mod.community !== undefined) {
        existing.community = mod.community;
      }
    }
  }

  return Array.from(seen.values());
}

/** Escape pipe characters inside GFM table cells. */
function escapePipe(s: string): string {
  return s.replace(/\|/g, "\\|");
}

/** Minimal markdown escaping for headings — escapes leading `#` in symbol names. */
function escapeMarkdown(s: string): string {
  return s.replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
