/**
 * Comprehensive unit tests for OnboardingComposer.
 *
 * Coverage:
 * - Snapshot tests for all 5 outputs (populated fixture)
 * - Empty inputs → empty-state messages
 * - Determinism: render twice → byte-identical
 * - Sort verification (modules alphabetical, hotspots by score desc)
 * - writeAll: creates dir; file absent path; marker preserves above; missing marker throws
 * - Performance: 1000-element inputs render in <100ms
 * - NaN score sorted last with "score unavailable" note
 * - Duplicate module names dedup behavior
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, rm, writeFile, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { OnboardingComposer } from "../../src/graph/onboarding-composer.js";
import type { OnboardingInputs } from "../../src/graph/types.js";

// ── Fixtures ───────────────────────────────────────────────────────

const POPULATED_INPUTS: OnboardingInputs = {
  status: { tokensaveVersion: "6.0.0-beta.1", indexedFileCount: 42 },
  hotspots: [
    { symbol: "parseGraph", file: "src/graph/parser.ts", line: 10, score: 95, reason: "High cyclomatic complexity" },
    { symbol: "buildIndex", file: "src/graph/indexer.ts", line: 55, score: 80, reason: "Large function" },
    { symbol: "resolveImports", file: "src/graph/resolver.ts", line: 22, score: 60 },
    { symbol: "lowScore", file: "src/other.ts", line: 1, score: 10 },
  ],
  deadCode: [
    { symbol: "legacyHelper", file: "src/utils/legacy.ts", line: 5 },
    { symbol: "oldParser", file: "src/graph/old-parser.ts", line: 88 },
  ],
  circular: [
    { cycle: ["src/a.ts", "src/b.ts", "src/a.ts"] },
  ],
  largest: [
    { symbol: "BigClass", file: "src/big.ts", line: 1, loc: 500 },
  ],
  moduleApis: [
    {
      module: "graph",
      community: "core",
      symbols: [
        { name: "GraphClient", file: "src/graph/client.ts", line: 10, hasInternalCallers: true },
        { name: "buildIndex", file: "src/graph/indexer.ts", line: 55, hasInternalCallers: false },
      ],
    },
    {
      module: "contracts",
      community: "core",
      symbols: [
        { name: "SprintContract", file: "src/contracts/sprint-contract.ts", line: 1, hasInternalCallers: true },
      ],
    },
    {
      module: "utils",
      community: "support",
      symbols: [
        { name: "assertNever", file: "src/graph/types.ts", line: 109, hasInternalCallers: false },
      ],
    },
  ],
  files: [
    { path: "src/graph/client.ts", symbols: 3 },
    { path: "src/graph/types.ts", symbols: 8 },
  ],
};

const EMPTY_INPUTS: OnboardingInputs = {
  status: { tokensaveVersion: "6.0.0-beta.1", indexedFileCount: 0 },
  hotspots: [],
  deadCode: [],
  circular: [],
  largest: [],
  moduleApis: [],
  files: [],
};

const MARKER = "<!-- generated by agent-bober — DO NOT EDIT below this line -->";

// ── Setup/teardown ─────────────────────────────────────────────────

let tmp: string;
beforeEach(async () => {
  tmp = await mkdtemp(join(tmpdir(), "bober-onboarding-"));
});
afterEach(async () => {
  await rm(tmp, { recursive: true, force: true });
});

// ── render() — populated fixture ───────────────────────────────────

describe("OnboardingComposer.render() — populated fixture", () => {
  const composer = new OnboardingComposer();

  it("readme contains H1 title", () => {
    const { readme } = composer.render(POPULATED_INPUTS);
    expect(readme).toContain("# Onboarding — agent-bober graph");
  });

  it("readme contains generated-at ISO timestamp", () => {
    const { readme } = composer.render(POPULATED_INPUTS);
    expect(readme).toMatch(/_Generated at: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  });

  it("readme contains tokensaveVersion in summary paragraph", () => {
    const { readme } = composer.render(POPULATED_INPUTS);
    expect(readme).toContain("6.0.0-beta.1");
    expect(readme).toContain("42");
  });

  it("readme contains 5-bullet where-to-look list with relative links", () => {
    const { readme } = composer.render(POPULATED_INPUTS);
    expect(readme).toContain("./architecture-overview.md");
    expect(readme).toContain("./hotspots.md");
    expect(readme).toContain("./knowledge-gaps.md");
    expect(readme).toContain("./communities.md");
    expect(readme).toContain("./README.md");
  });

  it("architectureOverview contains H1 and H2 sections per module", () => {
    const { architectureOverview } = composer.render(POPULATED_INPUTS);
    expect(architectureOverview).toContain("# Architecture Overview");
    expect(architectureOverview).toContain("## contracts");
    expect(architectureOverview).toContain("## graph");
    expect(architectureOverview).toContain("## utils");
  });

  it("architectureOverview lists symbols with file:line", () => {
    const { architectureOverview } = composer.render(POPULATED_INPUTS);
    expect(architectureOverview).toContain("GraphClient");
    expect(architectureOverview).toContain("src/graph/client.ts:10");
  });

  it("hotspots contains H1 and GFM table", () => {
    const { hotspots } = composer.render(POPULATED_INPUTS);
    expect(hotspots).toContain("# Hotspots");
    expect(hotspots).toContain("| Symbol |");
    expect(hotspots).toContain("| --- |");
    expect(hotspots).toContain("parseGraph");
    expect(hotspots).toContain("High cyclomatic complexity");
  });

  it("knowledgeGaps contains H1 and two H2 sections", () => {
    const { knowledgeGaps } = composer.render(POPULATED_INPUTS);
    expect(knowledgeGaps).toContain("# Knowledge Gaps");
    expect(knowledgeGaps).toContain("## Potentially unused (dead code)");
    expect(knowledgeGaps).toContain("## Public APIs without internal callers");
    expect(knowledgeGaps).toContain("legacyHelper");
    expect(knowledgeGaps).toContain("buildIndex");
  });

  it("communities contains H1 and community sections", () => {
    const { communities } = composer.render(POPULATED_INPUTS);
    expect(communities).toContain("# Communities");
    expect(communities).toContain("## core");
    expect(communities).toContain("## support");
  });

  it("communities includes module count and symbol count", () => {
    const { communities } = composer.render(POPULATED_INPUTS);
    // core has 2 modules (graph + contracts)
    expect(communities).toMatch(/Module group with 2 modules/);
    // support has 1 module
    expect(communities).toMatch(/Module group with 1 module /);
  });
});

// ── render() — empty inputs ────────────────────────────────────────

describe("OnboardingComposer.render() — empty inputs", () => {
  const composer = new OnboardingComposer();

  it("readme: still renders title and where-to-look list", () => {
    const { readme } = composer.render(EMPTY_INPUTS);
    expect(readme).toContain("# Onboarding — agent-bober graph");
    expect(readme).toContain("./hotspots.md");
  });

  it("architectureOverview: empty state message", () => {
    const { architectureOverview } = composer.render(EMPTY_INPUTS);
    expect(architectureOverview).toContain("# Architecture Overview");
    expect(architectureOverview).toContain("_No modules found._");
  });

  it("hotspots: empty state message", () => {
    const { hotspots } = composer.render(EMPTY_INPUTS);
    expect(hotspots).toContain("# Hotspots");
    expect(hotspots).toContain("No hotspots detected in this codebase.");
  });

  it("knowledgeGaps: dead code empty state", () => {
    const { knowledgeGaps } = composer.render(EMPTY_INPUTS);
    expect(knowledgeGaps).toContain("No dead code detected.");
  });

  it("knowledgeGaps: uncalled APIs empty state", () => {
    const { knowledgeGaps } = composer.render(EMPTY_INPUTS);
    expect(knowledgeGaps).toContain("All public APIs have internal callers.");
  });

  it("communities: empty state message", () => {
    const { communities } = composer.render(EMPTY_INPUTS);
    expect(communities).toContain("# Communities");
    expect(communities).toContain("_No communities found._");
  });
});

// ── Determinism ────────────────────────────────────────────────────

describe("OnboardingComposer.render() — determinism", () => {
  it("renders byte-identical output on two consecutive calls", () => {
    const composer = new OnboardingComposer();
    // Use a fixed date to avoid timestamp differences
    const fixedDate = new Date("2026-05-24T12:00:00.000Z");
    const origDate = global.Date;
    global.Date = class extends origDate {
      constructor(...args: ConstructorParameters<typeof origDate>) {
        if (args.length === 0) {
          super(fixedDate.getTime());
        } else {
          // @ts-expect-error spread args
          super(...args);
        }
      }
      toISOString(): string {
        return fixedDate.toISOString();
      }
    } as unknown as typeof Date;

    try {
      const first = composer.render(POPULATED_INPUTS);
      const second = composer.render(POPULATED_INPUTS);

      expect(first.readme).toBe(second.readme);
      expect(first.architectureOverview).toBe(second.architectureOverview);
      expect(first.hotspots).toBe(second.hotspots);
      expect(first.knowledgeGaps).toBe(second.knowledgeGaps);
      expect(first.communities).toBe(second.communities);
    } finally {
      global.Date = origDate;
    }
  });
});

// ── Sort verification ──────────────────────────────────────────────

describe("OnboardingComposer.render() — sort verification", () => {
  const composer = new OnboardingComposer();

  it("architectureOverview modules are alphabetical", () => {
    const { architectureOverview } = composer.render(POPULATED_INPUTS);
    const h2Positions = ["contracts", "graph", "utils"].map((m) =>
      architectureOverview.indexOf(`## ${m}`),
    );
    expect(h2Positions[0]).toBeLessThan(h2Positions[1]!);
    expect(h2Positions[1]).toBeLessThan(h2Positions[2]!);
  });

  it("hotspots sorted by score descending (top entry has score 95)", () => {
    const { hotspots } = composer.render(POPULATED_INPUTS);
    const rows = hotspots.split("\n").filter((l) => l.startsWith("| ") && !l.startsWith("| Symbol") && !l.startsWith("| ---"));
    expect(rows[0]).toContain("parseGraph");
    expect(rows[0]).toContain("95");
  });

  it("hotspots with NaN score sorted last", () => {
    const inputs: OnboardingInputs = {
      ...POPULATED_INPUTS,
      hotspots: [
        { symbol: "normalFn", file: "src/a.ts", line: 1, score: 50 },
        { symbol: "nanFn", file: "src/b.ts", line: 2, score: NaN },
      ],
    };
    const { hotspots } = composer.render(inputs);
    const rows = hotspots.split("\n").filter((l) => l.startsWith("| ") && !l.startsWith("| Symbol") && !l.startsWith("| ---"));
    expect(rows[0]).toContain("normalFn");
    expect(rows[1]).toContain("nanFn");
    expect(rows[1]).toContain("score unavailable");
  });

  it("hotspots top 20 limit: only first 20 entries rendered when >20", () => {
    const manyHotspots = Array.from({ length: 25 }, (_, i) => ({
      symbol: `fn${String(i).padStart(2, "0")}`,
      file: "src/a.ts",
      line: i + 1,
      score: 25 - i,
    }));
    const inputs: OnboardingInputs = { ...POPULATED_INPUTS, hotspots: manyHotspots };
    const { hotspots } = composer.render(inputs);
    const rows = hotspots.split("\n").filter((l) => l.startsWith("| ") && !l.startsWith("| Symbol") && !l.startsWith("| ---"));
    expect(rows.length).toBe(20);
  });
});

// ── Duplicate module dedup ─────────────────────────────────────────

describe("OnboardingComposer.render() — duplicate module names", () => {
  it("deduplicates module names and merges symbols", () => {
    const inputs: OnboardingInputs = {
      ...EMPTY_INPUTS,
      moduleApis: [
        {
          module: "shared",
          community: "core",
          symbols: [{ name: "helper", file: "src/a.ts", line: 1, hasInternalCallers: true }],
        },
        {
          module: "shared",
          community: "core",
          symbols: [{ name: "otherHelper", file: "src/b.ts", line: 2, hasInternalCallers: false }],
        },
      ],
    };
    const { architectureOverview } = composer.render(inputs);
    // Should appear only once as a section
    const matches = architectureOverview.match(/## shared/g);
    expect(matches).toHaveLength(1);
    // Both symbols should be listed
    expect(architectureOverview).toContain("helper");
    expect(architectureOverview).toContain("otherHelper");
  });

  const composer = new OnboardingComposer();
});

// ── writeAll — filesystem tests ────────────────────────────────────

describe("OnboardingComposer.writeAll()", () => {
  const composer = new OnboardingComposer();

  it("creates dir if it does not exist", async () => {
    const dir = join(tmp, "new-subdir", "onboarding");
    const artifacts = composer.render(POPULATED_INPUTS);
    await composer.writeAll(artifacts, dir);

    const readme = await readFile(join(dir, "README.md"), "utf-8");
    expect(readme).toContain(MARKER);
    expect(readme).toContain("# Onboarding — agent-bober graph");
  });

  it("writes all 5 files with the marker prefix", async () => {
    const artifacts = composer.render(POPULATED_INPUTS);
    await composer.writeAll(artifacts, tmp);

    for (const filename of [
      "README.md",
      "architecture-overview.md",
      "hotspots.md",
      "knowledge-gaps.md",
      "communities.md",
    ]) {
      const content = await readFile(join(tmp, filename), "utf-8");
      expect(content).toContain(MARKER);
    }
  });

  it("file absent: writes ${MARKER}\\n\\n${content}", async () => {
    const artifacts = composer.render(POPULATED_INPUTS);
    await composer.writeAll(artifacts, tmp);

    const readme = await readFile(join(tmp, "README.md"), "utf-8");
    expect(readme.startsWith(`${MARKER}\n\n`)).toBe(true);
    expect(readme).toContain("# Onboarding — agent-bober graph");
  });

  it("file with marker: preserves content above the marker, replaces below", async () => {
    // Pre-write a file with human content above the marker
    const humanContent = "# My custom heading\n\nSome human notes here.\n\n";
    await writeFile(
      join(tmp, "README.md"),
      `${humanContent}${MARKER}\n\nOLD GENERATED CONTENT`,
      "utf-8",
    );

    const artifacts = composer.render(POPULATED_INPUTS);
    await composer.writeAll(artifacts, tmp);

    const updated = await readFile(join(tmp, "README.md"), "utf-8");
    // Human content above preserved
    expect(updated.startsWith(humanContent)).toBe(true);
    // Marker present
    expect(updated).toContain(MARKER);
    // Old content replaced
    expect(updated).not.toContain("OLD GENERATED CONTENT");
    // New content present
    expect(updated).toContain("# Onboarding — agent-bober graph");
  });

  it("file without marker: throws with clear error naming the file", async () => {
    // Write a file without the generation marker
    await writeFile(join(tmp, "README.md"), "# Human-written README\n\nNo marker here.", "utf-8");

    const artifacts = composer.render(POPULATED_INPUTS);
    await expect(composer.writeAll(artifacts, tmp)).rejects.toThrow(
      "Refusing to overwrite README.md: missing generation marker.",
    );
  });

  it("throws clear error for empty dir argument", async () => {
    const artifacts = composer.render(POPULATED_INPUTS);
    await expect(composer.writeAll(artifacts, "")).rejects.toThrow(
      "writeAll: dir argument must be a non-empty path.",
    );
  });
});

// ── Performance ────────────────────────────────────────────────────

describe("OnboardingComposer.render() — performance", () => {
  it("renders 1000-element inputs in <100ms", () => {
    const composer = new OnboardingComposer();

    const bigInputs: OnboardingInputs = {
      status: { tokensaveVersion: "6.0.0-beta.1", indexedFileCount: 5000 },
      hotspots: Array.from({ length: 1000 }, (_, i) => ({
        symbol: `fn${i}`,
        file: `src/module${i % 50}.ts`,
        line: (i % 100) + 1,
        score: 1000 - i,
        reason: `Reason for function ${i}`,
      })),
      deadCode: Array.from({ length: 1000 }, (_, i) => ({
        symbol: `dead${i}`,
        file: `src/dead${i % 20}.ts`,
        line: (i % 100) + 1,
      })),
      circular: Array.from({ length: 100 }, (_, i) => ({
        cycle: [`src/a${i}.ts`, `src/b${i}.ts`, `src/a${i}.ts`],
      })),
      largest: Array.from({ length: 100 }, (_, i) => ({
        symbol: `BigClass${i}`,
        file: `src/big${i}.ts`,
        line: 1,
        loc: 500 + i,
      })),
      moduleApis: Array.from({ length: 100 }, (_, i) => ({
        module: `module-${String(i).padStart(3, "0")}`,
        community: i % 5 === 0 ? "core" : i % 5 === 1 ? "utils" : i % 5 === 2 ? "api" : i % 5 === 3 ? "internal" : "external",
        symbols: Array.from({ length: 10 }, (__, j) => ({
          name: `Symbol${i}_${j}`,
          file: `src/module${i}.ts`,
          line: j + 1,
          hasInternalCallers: j % 2 === 0,
        })),
      })),
      files: Array.from({ length: 1000 }, (_, i) => ({
        path: `src/file${i}.ts`,
        symbols: i % 10,
      })),
    };

    const start = Date.now();
    const result = composer.render(bigInputs);
    const elapsed = Date.now() - start;

    expect(elapsed).toBeLessThan(100);
    // All 5 fields populated
    expect(result.readme.length).toBeGreaterThan(0);
    expect(result.architectureOverview.length).toBeGreaterThan(0);
    expect(result.hotspots.length).toBeGreaterThan(0);
    expect(result.knowledgeGaps.length).toBeGreaterThan(0);
    expect(result.communities.length).toBeGreaterThan(0);
  });
});

// ── Snapshot tests ─────────────────────────────────────────────────

describe("OnboardingComposer.render() — snapshot tests", () => {
  const composer = new OnboardingComposer();

  it("architectureOverview snapshot (3-module fixture, alphabetical)", () => {
    const { architectureOverview } = composer.render(POPULATED_INPUTS);
    // Verify alphabetical: contracts < graph < utils
    const contractsPos = architectureOverview.indexOf("## contracts");
    const graphPos = architectureOverview.indexOf("## graph");
    const utilsPos = architectureOverview.indexOf("## utils");
    expect(contractsPos).toBeLessThan(graphPos);
    expect(graphPos).toBeLessThan(utilsPos);
    // Has proper bullet format
    expect(architectureOverview).toMatch(/- `GraphClient` — src\/graph\/client\.ts:10/);
  });

  it("hotspots snapshot: top entry is highest score, table format correct", () => {
    const { hotspots } = composer.render(POPULATED_INPUTS);
    expect(hotspots).toContain("| Symbol | File:Line | Complexity Score | Why it matters |");
    const firstDataRow = hotspots.split("\n").find((l) => l.startsWith("| parseGraph"));
    expect(firstDataRow).toBeDefined();
    expect(firstDataRow).toContain("95");
    expect(firstDataRow).toContain("src/graph/parser.ts:10");
    expect(firstDataRow).toContain("High cyclomatic complexity");
  });

  it("knowledgeGaps snapshot: dead code and uncalled symbols listed", () => {
    const { knowledgeGaps } = composer.render(POPULATED_INPUTS);
    expect(knowledgeGaps).toContain("`legacyHelper` — src/utils/legacy.ts:5");
    expect(knowledgeGaps).toContain("`oldParser` — src/graph/old-parser.ts:88");
    // buildIndex is uncalled (hasInternalCallers: false) in 'graph' module
    expect(knowledgeGaps).toContain("`buildIndex` (graph)");
    // assertNever is uncalled in 'utils' module
    expect(knowledgeGaps).toContain("`assertNever` (utils)");
  });

  it("communities snapshot: member count in description", () => {
    const { communities } = composer.render(POPULATED_INPUTS);
    expect(communities).toContain("## core");
    expect(communities).toContain("## support");
  });
});
