import { readFile, writeFile, readdir } from "node:fs/promises";
import { join } from "node:path";

import type { ResearchDoc, ResearchSections } from "../orchestrator/research-agent.js";
import { ensureDir } from "./helpers.js";

const RESEARCH_DIR = ".bober/research";

function researchDir(projectRoot: string): string {
  return join(projectRoot, RESEARCH_DIR);
}

function researchPath(projectRoot: string, id: string): string {
  const safeId = id.replace(/[^a-zA-Z0-9_-]/g, "_");
  return join(researchDir(projectRoot), `${safeId}.md`);
}

/**
 * Serialize a ResearchDoc to markdown format for storage.
 */
function serializeToMarkdown(doc: ResearchDoc): string {
  const questionsList = doc.explorationQuestions
    .map((q, i) => `${i + 1}. ${q}`)
    .join("\n");

  return `# Research Document

**Research ID:** ${doc.id}
**Generated:** ${doc.generatedAt}
**Questions Explored:** ${doc.questionsAnswered}/${doc.explorationQuestions.length}
**Files Explored:** ${doc.filesExplored.length}

---

## Architecture Overview

${doc.sections.architectureOverview}

## Existing Patterns

${doc.sections.existingPatterns}

## Key Files

${doc.sections.keyFiles}

## Integration Points

${doc.sections.integrationPoints}

## Test Coverage

${doc.sections.testCoverage}

## Risk Areas

${doc.sections.riskAreas}

---

## Exploration Questions

${questionsList}

---

## Files Explored

${doc.filesExplored.map((f) => `- ${f}`).join("\n") || "None recorded."}

---

*Generated by bober.research — factual findings only, no implementation recommendations.*
`;
}

/**
 * Parse a markdown research document back into a ResearchDoc.
 * Used by readResearch() to reconstruct the structured type.
 */
function parseMarkdown(content: string, id: string): ResearchDoc {
  const extractSection = (heading: string): string => {
    const pattern = new RegExp(
      `## ${heading}\\n\\n([\\s\\S]*?)(?=\\n## |\\n---\\n|$)`,
    );
    const match = pattern.exec(content);
    return match ? match[1].trim() : "";
  };

  const sections: ResearchSections = {
    architectureOverview: extractSection("Architecture Overview"),
    existingPatterns: extractSection("Existing Patterns"),
    keyFiles: extractSection("Key Files"),
    integrationPoints: extractSection("Integration Points"),
    testCoverage: extractSection("Test Coverage"),
    riskAreas: extractSection("Risk Areas"),
  };

  // Extract metadata from the header block
  const generatedMatch = /\*\*Generated:\*\* (.+)/.exec(content);
  const generatedAt = generatedMatch ? generatedMatch[1].trim() : new Date().toISOString();

  // Extract exploration questions
  const questionsSection = extractSection("Exploration Questions");
  const explorationQuestions = questionsSection
    .split("\n")
    .filter((line) => /^\d+\.\s/.test(line))
    .map((line) => line.replace(/^\d+\.\s+/, "").trim())
    .filter(Boolean);

  // Extract files explored
  const filesSection = extractSection("Files Explored");
  const filesExplored = filesSection
    .split("\n")
    .filter((line) => line.startsWith("- "))
    .map((line) => line.slice(2).trim())
    .filter(Boolean);

  const questionsAnsweredMatch = /\*\*Questions Explored:\*\* (\d+)\//.exec(content);
  const questionsAnswered = questionsAnsweredMatch
    ? parseInt(questionsAnsweredMatch[1], 10)
    : explorationQuestions.length;

  return {
    id,
    generatedAt,
    explorationQuestions,
    sections,
    filesExplored,
    questionsAnswered,
  };
}

/**
 * Save a research document to disk as a markdown file.
 * Overwrites any existing document with the same id.
 */
export async function saveResearch(
  projectRoot: string,
  doc: ResearchDoc,
): Promise<void> {
  await ensureDir(researchDir(projectRoot));

  const filePath = researchPath(projectRoot, doc.id);
  const markdown = serializeToMarkdown(doc);
  await writeFile(filePath, markdown, "utf-8");
}

/**
 * Read a research document by id.
 * Throws if not found.
 */
export async function readResearch(
  projectRoot: string,
  id: string,
): Promise<ResearchDoc> {
  const filePath = researchPath(projectRoot, id);

  let content: string;
  try {
    content = await readFile(filePath, "utf-8");
  } catch (err) {
    throw new Error(
      `Research document "${id}" not found: ${err instanceof Error ? err.message : String(err)}`,
      { cause: err },
    );
  }

  return parseMarkdown(content, id);
}

/**
 * List all saved research document IDs, sorted by filename.
 */
export async function listResearch(projectRoot: string): Promise<string[]> {
  const dir = researchDir(projectRoot);

  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    // Directory doesn't exist yet
    return [];
  }

  return entries
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => f.slice(0, -3)); // strip .md extension
}
